---
# Source: nats/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: default
  labels:
    helm.sh/chart: nats-0.15.1
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: nats
    app.kubernetes.io/version: "2.7.4"
    app.kubernetes.io/managed-by: Helm
data:
  nats.conf: |
    # NATS Clients Port
    port: 4222

    # PID file shared with configuration reloader.
    pid_file: "/var/run/nats/nats.pid"

    ###############
    #             #
    # Monitoring  #
    #             #
    ###############
    http: 8222
    server_name:$POD_NAME
    #####################
    #                   #
    # TLS Configuration #
    #                   #
    #####################
    tls {
        cert_file: /etc/nats-certs/clients/nats-server-tls/tls.crt
        key_file:  /etc/nats-certs/clients/nats-server-tls/tls.key
        ca_file: /etc/nats-certs/clients/nats-server-tls/ca.crt
        verify_and_map: true
        timeout: 5s
    }
    ###################################
    #                                 #
    # NATS JetStream                  #
    #                                 #
    ###################################
    jetstream {
      max_mem: 2Gi
      store_dir: /data/

      max_file:1Gi
    }
    ###################################
    #                                 #
    # NATS Full Mesh Clustering Setup #
    #                                 #
    ###################################
    cluster {
      port: 6222
      name: nats

      routes = [
        nats://nats-0.nats.default.svc.cluster.local:6222,nats://nats-1.nats.default.svc.cluster.local:6222,nats://nats-2.nats.default.svc.cluster.local:6222,
        
      ]
      cluster_advertise: $CLUSTER_ADVERTISE

      connect_retries: 120
    }
    debug: true
    lame_duck_grace_period: 10s
    lame_duck_duration: 30s
    ##################
    #                #
    # Authorization  #
    #                #
    ##################
    system_account: SYS
    authorization {
      timeout: 5s
    }

    accounts:{"A":{"jetstream":true,"users":[{"user":"CN=nack-a"}]},"B":{"jetstream":true,"users":[{"user":"CN=nack-b"}]},"SYS":{"users":[{"user":"CN=nats-sys-user"}]}}
